### ISSUE TITLE
About the input data

### ISSUE THREAD

**Issue by lucky9-cyou** [AIR-DISCOVER/LASST#1]
I want to repeat the experiment, but I can not know how to process raw data. Can you provide any processed data or some scripts for preprocessing? Thank you very much.

**Comment by jxbbb** [comment]
Thanks for your question. Actually the data does not need to be preprocessed and you just need to place it on the correct path. I have uploaded an example of meshes in scannet (in "data/source_meshes/scannet") and have fixed the FULL_PATH and FULL_MESH_PATH in "src/local.py". Now the experiment can run directly with the script "scripts/scannet_go.sh". The example of meshes in scenenn will be uploaded soon. Please let me konw if you have any other questions.

**Comment by jxbbb** [comment]
> I want to repeat the experiment, but I can not know how to process raw data. Can you provide any processed data or some scripts for preprocessing? Thank you very much.

Thanks for your question. Actually the data does not need to be preprocessed and you just need to place it on the correct path. I have uploaded an example of meshes in scannet (in "data/source_meshes/scannet") and have fixed the FULL_PATH and FULL_MESH_PATH in "src/local.py". Now the experiment can run directly with the script "scripts/scannet_go.sh". The example of meshes in scenenn will be uploaded soon. Please let me konw if you have any other questions.

**Comment by lucky9-cyou** [comment]
Thank you very much. I successfully ran the demo and tried other data. I will close this issue.
